git:
  autoFetch: false
  pagers:
    - pager: delta --dark --paging=never --tabs=4
gui:
  nerdFontsVersion: "3"
  spinner:
    frames:
      - "⣷"
      - "⣯"
      - "⣟"
      - "⡿"
      - "⢿"
      - "⣻"
      - "⣽"
      - "⣾"
  theme:
    selectedLineBgColor:
      - black
notARepository: skip
